global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100'] # Host Metrics
  - job_name: 'sentiment_project'
    static_configs:
      - targets: ['192.168.1.166:8000'] # Application metrics